# Generated by Django 3.2.3 on 2021-07-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210703_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_who_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
